class AppAssets {
  AppAssets();
  static final String home = 'assets/svg/home.svg';
  static final String offer = 'assets/svg/offer.svg';
  static final String order = 'assets/svg/order.svg';
  static final String myOrder = 'assets/svg/myOrder.svg';
  static final String menu = 'assets/svg/menu.svg';
  static final String shoppingCart = 'assets/svg/shopping-cart.svg';
  static final String redFerrari = 'assets/image/red_ferrari.png';
  static final String success = 'assets/image/success.png';
  static final String logo = 'assets/image/logo.png';
  static final String purpleLogo = 'assets/image/purple_logo.png';
  static final String tyre = 'assets/image/tyre.png';
  static final String pic = 'assets/image/eclipes.png';
  static final String pic2 = 'assets/image/yellow_bg_photo.png';
  static final String tyreWheel = 'assets/image/wheel.png';
  static final String engine = 'assets/image/engine.png';
  static final String iCar = 'assets/image/icar.png';
  static final String yellowLogo = 'assets/image/yellow_logo.png';
  static final String purpleAndYellowLogo = 'assets/svg/pellow.svg';
  static final String purpleBar = 'assets/svg/purple_bar.svg';
  static final String whiteBar = 'assets/svg/white_bar.svg';
  static final String yellow = 'assets/svg/yellow_bar.svg';
  static final String address = 'assets/svg/address.svg';
  static final String creditCard = 'assets/svg/credit-card-payment.svg';
  static final String help = 'assets/svg/help-web-button.svg';
  static final String privacyPolicy = 'assets/svg/privacy-policy.svg';
  static final String sent = 'assets/svg/sent.svg';
  static final String settings = 'assets/svg/settings.svg';
  static final String user = 'assets/svg/user.svg';
  static final String yellowAddress = 'assets/svg/yellow_address.svg';
  static final String english = 'assets/svg/english.svg';
  static final String french = 'assets/svg/french.svg';
  static final String germany = 'assets/svg/germany.svg';
  static final String chinese = 'assets/svg/chinese.svg';
  static final String japan = 'assets/svg/japan.svg';
  static final String turkey = 'assets/svg/turkey.svg';
}